version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8551:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
networks:
        default:
        driver: bridge
        ipam:
        config:
                - subnet: 172.16.57.0/24