version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8531:8531"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
                network_mode: bridge
